name: 'Auto-version: Finish Release'
description: 'Finished up a release for KMMBridge'
author: 'Kevin Galligan'

inputs:
  commitMessage:
    description: 'Message for Package.swift commit'
    required: true
  tagMessage:
    description: 'Message for release tag'
    required: true
  tagVersion:
    description: 'The release version'
    required: true
  branchName:
    description: 'Branch name'
    required: true

runs:
  using: node20
  main: dist/index.js
